application: charityspotter
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/*
  script: _go_app

- url: /(.+)
  static_files: frontend/\1
  upload: frontend/(.+)

- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

